name: Docker

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "0 0 * * *"

env:
  IMAGE_NAME: sage-notebook
  SAGE_VERSION: 9.2

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Login to ghcr.io
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args:
          - SAGE_VERSION: {{ env.SAGE_VERSION }}
          push: true
          tags: |
            docker.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            docker.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{github.run_number}}
            docker.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.SAGE_VERSION }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{github.run_number}}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.SAGE_VERSION }}
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
